// A custom exception class that is used to differentiate between handled
// exceptions such as bad user input and unhandled exceptions such as
// those generated by the .NET framework caused by things like faulty code.

namespace WebApi.Helpers;
using System.Globalization;

public class AppException : Exception
{
    public AppException() : base() {}
    
    public AppException(string message) : base(message) { }

    public AppException(string message, params object[] args)
        : base(String.Format(CultureInfo.CurrentCulture, message, args))
        { 
        }
}